[build]
	command="npm run build"
	publish="build"

[context.production.environment]
	BRANCH="production"

[context.branch-deploy.environment]
	BRANCH="branch-deploy"

[[redirects]]
	from="/*"
	to="/index.html"
	status=200
	force = false
